import { createElement, useState } from 'react';
const MODES = ['Workspace', 'Agent', 'Sessions'];
const timestamp = (value) => { const time = new Date(value ?? 0).getTime(); return Number.isNaN(time) ? 0 : time; };
export function formatRelativeTime(iso, now = Date.now()) { if (!iso) return ''; const minutes = Math.max(0, Math.round((now - timestamp(iso)) / 60000)); if (minutes < 1) return 'now'; if (minutes < 60) return `${minutes}m`; const hours = Math.round(minutes / 60); return hours < 24 ? `${hours}h` : `${Math.round(hours / 24)}d`; }
export function groupSessions(sessions, mode) { if (mode === 'Sessions') return [{ key: 'sessions', label: null, sessions }]; const groups = new Map(); for (const session of sessions) { const key = mode === 'Workspace' ? session.workspaceKey ?? `cwd:${session.cwd ?? 'unknown'}` : session.agent ?? 'Unknown agent'; const label = mode === 'Workspace' ? session.workspaceName ?? 'Unknown workspace' : session.agent ?? 'Unknown agent'; const group = groups.get(key) ?? { key, label, sessions: [] }; group.sessions.push(session); groups.set(key, group); } return [...groups.values()]; }
async function copyToClipboard(markdown) { if (!navigator.clipboard?.writeText) throw new Error('Clipboard unavailable'); await navigator.clipboard.writeText(markdown); }
function statusClass() { return 'is-neutral'; }

export function UsageBar({ resourceStatus, expanded, onToggle, alwaysOnTop, onPin, onHide, onQuit }) {
  const codex = resourceStatus?.agents?.find((agent) => agent.agent === 'codex');
  const resources = codex?.resources ?? [];
  const windowLabel = (minutes) => minutes === 300 ? '5h' : minutes === 10080 ? '7d' : `${minutes}m`;
  const codexText = resources.length ? `Codex · ${resources.map((resource) => `${windowLabel(resource.windowDurationMinutes)} ${resource.percentUsed}%`).join(' · ')}` : 'Codex —';
  const title = resources.length ? resources.map((resource) => `${windowLabel(resource.windowDurationMinutes)}: ${resource.percentUsed}% used · resets ${new Date(resource.resetsAt * 1000).toLocaleString()}${resource.plan ? ` · ${resource.plan}` : ''}`).join('\n') : 'Codex quota unavailable';
  return createElement('header', { className: 'margin-usage-bar', 'data-window-drag-region': true },
    createElement('span', { className: 'margin-usage-viewport', title }, createElement('span', { className: 'margin-usage-agent', 'data-agent': 'codex' }, codexText), createElement('span', { className: 'margin-usage-agent', 'data-agent': 'claude-code' }, 'Claude —')),
    createElement('div', { className: 'margin-control-dock', 'data-window-drag-region': false },
      createElement('button', { type: 'button', className: 'margin-usage-toggle', onClick: onToggle, 'aria-expanded': expanded, 'aria-label': expanded ? 'Collapse sessions' : 'Expand sessions', title: expanded ? 'Collapse' : 'Expand' }, expanded ? '▴' : '▾'),
      createElement('button', { type: 'button', className: `margin-window-control ${alwaysOnTop ? 'is-active' : ''}`, onClick: onPin, title: 'Pin', 'aria-label': 'Pin', 'aria-pressed': alwaysOnTop }, '⌖'),
      createElement('button', { type: 'button', className: 'margin-window-control', onClick: onHide, title: 'Hide', 'aria-label': 'Hide' }, '—'),
      createElement('button', { type: 'button', className: 'margin-window-control is-quit', onClick: onQuit, title: 'Quit', 'aria-label': 'Quit' }, '×')));
}

export function SessionBoard({ api, sessions, loading, error, onRetry, settings, onSettingsChange, onToast, alwaysOnTop, onPin }) {
  const [mode, setMode] = useState('Workspace'); const [showSettings, setShowSettings] = useState(false); const [actionState, setActionState] = useState({}); const groups = groupSessions(sessions, mode);
  async function handoff(session, action) { if (actionState[session.id] === 'working') return; setActionState((state) => ({ ...state, [session.id]: 'working' })); try { const generated = await api.generateHandoff({ sessionId: session.id, repo: session.cwd }); if (!generated.ok) throw new Error(generated.error?.message ?? 'Handoff generation failed'); if (action === 'copy') { await copyToClipboard(generated.data.markdown); onToast?.('✓ Copied'); } else { const saved = await api.saveToWorkspace({ repo: generated.data.session?.cwd ?? session.cwd, markdown: generated.data.markdown }); if (!saved.ok || !saved.data?.path) throw new Error(saved.error?.message ?? 'Handoff write was not confirmed'); onToast?.(settings.saveConfirmation === 'compact' ? '✓ Saved' : `✓ Saved · ${saved.data.path}`); } setActionState((state) => ({ ...state, [session.id]: action === 'copy' ? 'copied' : 'saved' })); } catch (failure) { setActionState((state) => ({ ...state, [session.id]: 'error' })); onToast?.(`${action === 'copy' ? 'Copy' : 'Save'} failed · ${failure.message || 'Unknown error'}`, 'error'); } }
  const list = createElement('div', { className: 'margin-board-scroll' },
    groups.map((group) => createElement('section', { className: 'margin-session-group', key: group.key },
      group.label ? createElement('header', { className: 'margin-session-group-label' }, group.label) : null,
      group.sessions.map((session) => createElement(SessionRow, { key: session.id, session, mode, state: actionState[session.id], onHandoff: handoff }))
    ))
  );
  const content = showSettings ? createElement(Settings, { settings, onSettingsChange, alwaysOnTop, onPin }) : loading ? createElement('p', { className: 'margin-board-message' }, 'Loading sessions…') : error ? createElement('div', { className: 'margin-board-message margin-error', role: 'alert' }, error, ' ', createElement('button', { type: 'button', onClick: onRetry }, 'Retry')) : !sessions.length ? createElement('p', { className: 'margin-board-message' }, 'No Codex sessions found on this machine.') : list;
  return createElement('section', { className: 'margin-board', 'aria-label': 'Session Board' }, createElement('div', { className: 'margin-board-modes', role: 'tablist', 'aria-label': 'Session grouping' }, MODES.map((item) => createElement('button', { type: 'button', role: 'tab', key: item, onClick: () => { setMode(item); setShowSettings(false); }, 'aria-selected': !showSettings && item === mode, className: !showSettings && item === mode ? 'is-selected' : '' }, item)), createElement('button', { type: 'button', className: `margin-settings-button ${showSettings ? 'is-selected' : ''}`, title: 'Settings', 'aria-label': 'Settings', onClick: () => setShowSettings((value) => !value) }, '⚙')), content);
}
function Settings({ settings, onSettingsChange, alwaysOnTop, onPin }) { return createElement('div', { className: 'margin-settings-panel' }, createElement('section', null, createElement('h2', null, 'Display'), createElement('label', null, createElement('input', { type: 'checkbox', checked: settings.showSummary, onChange: (event) => onSettingsChange({ showSummary: event.target.checked }) }), ' Show workspace/session summary')), createElement('section', null, createElement('h2', null, 'Window'), createElement('label', null, createElement('input', { type: 'checkbox', checked: Boolean(alwaysOnTop), onChange: onPin }), ' Always on top')), createElement('section', null, createElement('h2', null, 'Feedback'), createElement('label', null, 'Save confirmation ', createElement('select', { value: settings.saveConfirmation, onChange: (event) => onSettingsChange({ saveConfirmation: event.target.value }) }, createElement('option', { value: 'full' }, 'Full path'), createElement('option', { value: 'compact' }, 'Compact'))))); }
function SessionRow({ session, mode, state, onHandoff }) { const title = session.label ?? session.summary ?? session.id; const context = mode === 'Agent' ? session.workspaceName ?? session.cwd ?? '' : mode === 'Sessions' ? [session.agent ?? 'Unknown', session.workspaceName ?? session.cwd ?? ''].filter(Boolean).join(' · ') : session.agent ?? 'Unknown'; return createElement('div', { className: 'margin-session-row', 'data-session-id': session.id, 'data-mode': mode.toLowerCase() }, createElement('span', { className: `margin-status-dot ${statusClass()}`, title: 'Historical session; no runtime state is available' }), createElement('span', { className: 'margin-row-context', title: context }, context), createElement('span', { className: 'margin-row-title', title }, title), createElement('span', { className: 'margin-row-right-slot' }, createElement('span', { className: 'margin-row-time' }, formatRelativeTime(session.updatedAt)), createElement('span', { className: 'margin-row-actions' }, createElement('button', { type: 'button', disabled: state === 'working', onClick: () => onHandoff(session, 'copy') }, state === 'working' ? '…' : 'Copy'), createElement('button', { type: 'button', disabled: state === 'working', onClick: () => onHandoff(session, 'save') }, 'Save')))); }
